Text menu - on swtich/case
infoshareacademy/jjdzr8-javaholics pull request #5
Opened 2022-12-04 11:27 UTC by kamkol

2022-12-04 11:28 UTC, kamkol commented
Javaholics [JJDZR8JH-3] - Menu tekstowe

2022-12-11 08:47 UTC, michalgolombiewski requested changes

2022-12-11 08:47 UTC, michalgolombiewski commented on src/main/java/org/infoshareacademy/javaholics/Menu.java
> +
Proponuję, aby po wybraniu opcji Menu była mozliwość powrotu do Menu głównego np. poprzez '0'. No i obsługa wyjątków ;)

2022-12-18 11:05 UTC, karolpikiel commented on src/main/java/org/infoshareacademy/javaholics/App.java
>  public class App
Proponuje by menu bylo w osobnej klasie/było osbnym obiektem a nie w App (tam był dawał tylko główną mechanikę aplikacji) by jak je zminieac to pracowac nad osobna klasa a nie nad App

2022-12-18 11:05 UTC, karolpikiel commented on src/main/java/org/infoshareacademy/javaholics/App.java
>      }
Brakuje mi obiektów z submenu, moze jak osobnych klas lub jednej klasy ze wszystkimmi menu/instrukcjami wchodzenia do nich i wychodzenia (tak naprawdę wyświetlania) przykladowo w schemacie:

mamy menu głonwne ---> klikamy na klawiaturze 1 (nastepuje sprawdzenie czy liczba  nie enter czy litera) - pojawia się submenu "Dodaj nową trase" z polceniem w stylu "By dodac nową trase wpisz ...." i powrót do głownego menu wcisnij 0, i tak dla każdej opcji

2022-12-18 11:05 UTC, karolpikiel commented on src/main/java/org/infoshareacademy/javaholics/Menu.java
> +            switch (scanner.nextInt()) {
Wyjątki:
- liczby ujmene, stringi, przecinki, sam enter, zero jak w menu nie ma zero, liczba poza zakresem
tu przyklad z zdania lotto:
boolean flagRange;

        do {
            flagRange = false;

            try {
                range = rangeScanner.nextInt();
                if (range <= 0) {
                    throw new ArithmeticException("Wprowadzono liczbę ujemną lub zero.");
                } else {
                    System.out.println("Wprowadzono: " + range);
                }


            } catch (InputMismatchException exception) {
                System.out.println("Proszę podaj właściwe dane - liczbę całkowitą dodatnią.");
                flagRange = true;
                rangeScanner.nextLine();
            } catch (ArithmeticException e) {
                System.out.println(e.getMessage());
                flagRange = true;
                rangeScanner.nextLine();
            }
        }
        while (flagRange);

2022-12-18 11:34 UTC, kamkol commented on src/main/java/org/infoshareacademy/javaholics/App.java
>  public class App
Naniosłem zmiany w App oraz dodałem try/catch na wyjątki.
Dzięki!

2022-12-30 10:55 UTC, karolpikiel approved these changes

2022-12-30 14:18 UTC, closed without merging